### ISSUE TITLE
R.js - Path must be a string

### ISSUE THREAD

**Issue by JohnRSim** [guybedford/require-css#231]
When optimising the css with r.js i'm getting the following error below?

```
define(
    [
        'Action',
        'SPA_css!./adminPanel'
    ],
    function (Action) {
```

```
{
                optimize: 'none',//'uglify',
				preserveLicenseComments: false,
                useStrict: true,
			    paths: {
					hgn: 				'../../lib/requirejs/hgn',
					hogan: 				'../../lib/requirejs/hogan',
	        		text: 				'../../lib/requirejs/text',
					Action:'empty:',
					//css:'empty',
					css: 			'empty:',
					normalize:'empty:',
					SPA_css: 			'../../lib/requirejs/css',
				},
				stubModules : ['text', 'hgn', 'hogan'],
				isBuild :true,
      			findNestedDependencies: true,
				inlineJSON:false,
				inlineText: false,
				optimizeCss: "standard.keepLines.keepWhitespace",
			    // configure hgn! plugin
			    hgn: {
			        templateExtension: '.mustache',
			        compilationOptions: {}
			    },
			    map: {
			        // '*' means all modules will get 'jquery-private'
			        // for their 'jquery' dependency.
			        //'*': { 'jquery': 'jquery-private' },

			        // 'jquery-private' wants the real jQuery module
			        // though. If this line was not here, there would
			        // be an unresolvable cyclic dependency.
			        //'jquery-private': { 'jquery': 'jquery' }

			        //used with https://github.com/guybedford/require-css to import spa skins
			        '*': {
			            'SPA_css': '../../lib/requirejs/css'
			        }
			    },
			    //urlArgs: { 'bust': Date.now() }, // disable on prod!.. enables cache on scripts. only needed if cache is enabled on browsers.
			    waitSeconds: 60,
			    xhtml: false
            };
```

```
[15:11:54] Optimizing adminPanelTpl.js
TypeError: Path must be a string. Received [Function]
In module tree:
    adminPanelTpl
      ../../lib/requirejs/css


events.js:160
      throw er; // Unhandled 'error' event
      ^
 Error: TypeError: Path must be a string. Received [Function]
In module tree:
    adminPanelTpl
      ../../lib/requirejs/css

    at assertPath (path.js:7:11)

    at C:\work\git\nas\gulp\node_modules\requirejs\bin\r.js:26659:19
    at C:\work\git\nas\gulp\node_modules\requirejs\bin\r.js:3059:39
    at C:\work\git\nas\gulp\node_modules\requirejs\bin\r.js:2999:25
    at Function.prim.nextTick (C:\work\git\nas\gulp\node_modules\requirejs\bin\r.js:26410:9)
    at Object.p.errback (C:\work\git\nas\gulp\node_modules\requirejs\bin\r.js:2998:26)
    at Object.p.callback (C:\work\git\nas\gulp\node_modules\requirejs\bin\r.js:2984:23)
    at Object.p.promise.then (C:\work\git\nas\gulp\node_modules\requirejs\bin\r.js:3038:23)
    at build (C:\work\git\nas\gulp\node_modules\requirejs\bin\r.js:26616:12)
    at runBuild (C:\work\git\nas\gulp\node_modules\requirejs\bin\r.js:28624:17)
    at Object.context.execCb (C:\work\git\nas\gulp\node_modules\requirejs\bin\r.js:1946:33)
```

**Comment by KTamas** [comment]
I have the exact same issue

**Comment by VincenzoAsciolla** [comment]
I had the same issue using node v6.10.2 on macOS Sierra v10.12.3.
I solved downgrading the node version to 4.7.3.

**Comment by AStoker** [comment]
Wish I knew why downgrading worked...

**Comment by AStoker** [comment]
It's ultimately breaking on this line (https://github.com/guybedford/require-css/blob/master/css-builder.js#L130).
```
if (!siteRoot) {
      siteRoot = path.resolve(config.dir || path.dirname(config.out), config.siteRoot || '.') + '/';
      if (isWindows)
        siteRoot = siteRoot.replace(/\\/g, '/');
}
```
`config.out` is a function instead of the string that it's expecting. Despite having set the `out` property to be a string in the rjs config, it seems to be overwritten with this function
```
function (text, sourceMap) {
    output = text;
    sourceMapOutput = sourceMap;
  }
```
No idea where that comes from though, can't seem to find references to it.
